# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4912de548d7dbccd6b78c3c0a3c017f55e2cdcd9c42bd0c9765a997c0ee1afa0e4109d66ac9b96e35db6aac87d08fded9026835fc54c5aed50a057ecbf5ec381

test:
  secret_key_base: 78f18df19ceee75d339206af0de5ffccbddaf06677e041d272cd562e49ff150c4f371db604aac90405a8ccd63f565d48ff101998ca3c6c3fb6247c827c8b8935

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
